% Copyright 2023 Andrea Vaccari (avaccari@middlebury.edu)

% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.

% --- Add GUI elements
function handles = addGuiElements(handles)

% Add copyright info
txt = {'Copyright (C) 2023 Andrea Vaccari (avaccari@middlebury.edy)', ...
       '', ...
       'This program is free software: you can redistribute it and/or modify', ...
       'it under the terms of the GNU General Public License as published by', ...
       'the Free Software Foundation, either version 3 of the License, or', ...
       'any later version.', ...
       'This program is distributed in the hope that it will be useful,', ...
       'but WITHOUT ANY WARRANTY; without even the implied warranty of', ...
       'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the', ...
       'GNU General Public License for more details.', ...
       '', ...
       'You should have received a copy of the GNU General Public License', ...
       'along with this program.  If not, see <http://www.gnu.org/licenses/>.', ...
       '', ...
       'For "xlwrite":',...
       'Copyright (C) 2013 Alec de Zegher', ...
       'Redistribution and use in source and binary forms, with or without', ...
       'modification, are permitted provided that the following conditions are', ...
       'met:', ...
       '', ...
       '    * Redistributions of source code must retain the above copyright', ...
       '      notice, this list of conditions and the following disclaimer.', ...
       '    * Redistributions in binary form must reproduce the above copyright', ...
       '      notice, this list of conditions and the following disclaimer in', ...
       '      the documentation and/or other materials provided with the distribution', ...
       '', ...
       'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"', ...
       'AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE', ...
       'IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE', ...
       'ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE', ...
       'LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR', ...
       'CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF', ...
       'SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS', ...
       'INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN', ...
       'CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)', ...
       'ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE', ...
       'POSSIBILITY OF SUCH DAMAGE.', ...
       '', ...
       '"xlwrite" uses the Apache POI library under the', ...
       'Apache License, Version 2.0, January 2004', ...
       'http://www.apache.org/licenses/', ...
       '', ...
       'Some of the colormaps upsed were designed by Peter Kovesi:', ...
       'Peter Kovesi. Good Colour Maps: How to Design Them.', ...
       'arXiv:1509.03700 [cs.GR] 2015'};
   
uicontrol('parent', handles.mainGui, ...
         'style', 'text', ...
         'string', ['Lymph4D ', char(169), '2023 - Andrea Vaccari'], ...
         'units', 'normalized', ...
         'position', [0.85, 0.0, 0.15, 0.025], ...
         'enable', 'inactive', ...
         'ButtonDownFcn', @(src, evt)msgbox(txt, 'Copyright'));